// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PutovanjaAPI.Context;

namespace PutovanjaAPI.Migrations
{
    [DbContext(typeof(MojContext))]
    [Migration("20190622225629_DodanoPoljeOdobreno")]
    partial class DodanoPoljeOdobreno
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PutovanjaAPI.Models.Odrediste", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv");

                    b.HasKey("Id");

                    b.ToTable("Odrediste");
                });

            modelBuilder.Entity("PutovanjaAPI.Models.Uposlenik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("Ime");

                    b.Property<string>("Prezime");

                    b.HasKey("Id");

                    b.ToTable("Uposlenik");
                });

            modelBuilder.Entity("PutovanjaAPI.Models.UposlenikOdrediste", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DatumPolaska");

                    b.Property<DateTime>("DatumPovratka");

                    b.Property<bool>("Odobreno");

                    b.Property<int>("OdredisteId");

                    b.Property<int>("UposlenikId");

                    b.HasKey("Id");

                    b.HasIndex("OdredisteId");

                    b.HasIndex("UposlenikId");

                    b.ToTable("UposlenikOdrediste");
                });

            modelBuilder.Entity("PutovanjaAPI.Models.UposlenikOdrediste", b =>
                {
                    b.HasOne("PutovanjaAPI.Models.Odrediste", "Odrediste")
                        .WithMany()
                        .HasForeignKey("OdredisteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PutovanjaAPI.Models.Uposlenik", "Uposlenik")
                        .WithMany()
                        .HasForeignKey("UposlenikId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
